# FC-alike/httpd 2.4 macros with failback
%{!?_httpd_apxs: %{expand: %%global _httpd_apxs %%{_sbindir}/apxs}}
%{!?_httpd_mmn: %{expand: %%global _httpd_mmn %%(cat %{_includedir}/httpd/.mmn || echo 0-0)}}
%{!?_httpd_confdir:    %{expand: %%global _httpd_confdir    %%{_sysconfdir}/httpd/conf.d}}
# /etc/httpd/conf.d with httpd < 2.4 and defined as /etc/httpd/conf.modules.d with httpd >= 2.4
%{!?_httpd_modconfdir: %{expand: %%global _httpd_modconfdir %%{_sysconfdir}/httpd/conf.d}}
%{!?_httpd_moddir:     %{expand: %%global _httpd_moddir     %%{_libdir}/httpd/modules}}
# http://fedoraproject.org/wiki/Packaging:Tmpfiles.d
%{!?_tmpfilesdir:     %{expand: %%global _tmpfilesdir       /lib/tmpfiles.d}}

Summary: A SAML 2.0 authentication module for the Apache Httpd Server
Name: mod_auth_mellon
Version: 0.9.1
Release: 1%{?dist}
Group: System Environment/Daemons
Source0: https://github.com/UNINETT/%{name}/releases/download/v%{version}/%{name}-%{version}.tar.gz
Source1: auth_mellon.conf
Source2: 10-auth_mellon.conf
Source3: mod_auth_mellon.conf
Source4: mellon_create_metadata.sh
License: GPLv2+
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: curl-devel, glib2-devel, httpd-devel, lasso-devel, openssl-devel, xmlsec1-devel
Requires: httpd-mmn = %{_httpd_mmn}
Requires: lasso >= 2.3.6
Url: https://github.com/UNINETT/mod_auth_mellon

%description
The mod_auth_mellon module is an authentication service that implements the
SAML 2.0 federation protocol. It grants access based on the attributes
received in assertions generated by a IdP server.

%prep
%setup -q -n %{name}-%{version}

%build
export APXS=%{_httpd_apxs}
%configure
make %{?_smp_mflags}

%install
rm -rf %{buildroot}
# install module
mkdir -p %{buildroot}%{_httpd_moddir}
install -m 755 .libs/%{name}.so %{buildroot}%{_httpd_moddir}

# install module configuration
mkdir -p %{buildroot}%{_httpd_confdir}
install -m 644 %{SOURCE1} %{buildroot}%{_httpd_confdir}
mkdir -p %{buildroot}%{_httpd_modconfdir}
install -m 644 %{SOURCE2} %{buildroot}%{_httpd_modconfdir}

mkdir -p %{buildroot}%{_tmpfilesdir}
install -m 644 %{SOURCE3} %{buildroot}%{_tmpfilesdir}
mkdir -p %{buildroot}/run/%{name}

# install script to generate metadata
mkdir -p %{buildroot}/%{_libexecdir}/%{name}
install -m 755 %{SOURCE4} %{buildroot}/%{_libexecdir}/%{name}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root)
%doc README COPYING
%config(noreplace) %{_httpd_modconfdir}/10-auth_mellon.conf
%config(noreplace) %{_httpd_confdir}/auth_mellon.conf
%{_httpd_moddir}/mod_auth_mellon.so
%{_tmpfilesdir}/mod_auth_mellon.conf
%{_libexecdir}/%{name}
%dir /run/%{name}/

%changelog
* Tue Sep 16 2014 Richard Clark <rclark@telnic.org> 0.9.1-1%{?dist}
- Update to 0.9.1
- Project migration to git
- Pull in changes from FC22 (rawhide) spec with EL6 fallbacks

* Mon Apr 28 2014 Richard Clark <rclark@telnic.org> 0.7.0-1%{?dist}
- Update to 0.7.0
- Remove auth_mellon.conf

* Tue Sep 11 2012 Benjamin Dauvergne <bdauvergne@entrouvert.com> 0.5.0-1%{?dist}
- Update to 0.5.0
- Remove auth_mellon.conf

* Tue Jan 25 2011 Jean-Marc Liger <jmliger@siris.sorbonne.fr> 0.3.0-1%{?dist}
- Updated to 0.3.0
- Rebuilt on CentOS 5

* Mon Aug 18 2009 Jean-Marc Liger <jmliger@siris.sorbonne.fr> 0.1.1-1%{?dist}
- Updated to 0.1.1
- Rebuilt on CentOS 5

* Sat Jan 17 2009 Jean-Marc Liger <jmliger@siris.sorbonne.fr> 0.1.0-1%{?dist}
- Updated to 0.1.0
- Added missing BuildRequires glib2-devel
- Rebuilt on CentOS 5

* Mon Aug 18 2008 Jean-Marc Liger <jmliger@siris.sorbonne.fr> 0.0.7-1%{?dist}
- Updated to 0.0.7
- Rebuilt on CentOS 5

* Fri Nov 16 2007 Jean-Marc Liger <jmliger@siris.sorbonne.fr> 0.0.6-1%{?dist}
- First 0.0.6
- Built on CentOS 5
